In [42]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.7.0


In [6]:
hello=tf.constant("hello ")

In [7]:
world=tf.constant("World")

In [8]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'helloWorld'


In [12]:
a=tf.constant(10)

In [13]:
b=tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
a/b

<tf.Tensor 'truediv:0' shape=() dtype=float64>

In [17]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [19]:
result

30

In [20]:
const=tf.constant(10)

In [22]:
fill_mat = tf.fill((4,4),10)

In [23]:
myzeros=tf.zeros((4,4))

In [24]:
myones=tf.ones((4,4))

In [25]:
myrandn=tf.random_normal((4,4),mean=0,stddev=1.0)

In [26]:
myrandu=tf.random_uniform((4,4),minval=0,maxval=1)

In [27]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [28]:
my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]

In [29]:
my_ops

[<tf.Tensor 'Const_6:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [30]:
sess = tf.InteractiveSession()

In [32]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.59993643 -0.36812365  0.43152249  1.2325294 ]
 [-1.10173249  0.10033043  0.29746935  1.04398894]
 [ 0.74198449 -0.01407063  0.90057194  1.32069254]
 [-0.12442997 -1.1868912  -1.10859072 -1.45404649]]


[[ 0.37153077  0.547001    0.97610426  0.27439928]
 [ 0.41409588  0.84457564  0.34905696  0.10469472]
 [ 0.35351503  0.94996285  0.24912047  0.1191653 ]
 [ 0.29053152  0.46646404  0.17224324  0.51339543]]




In [33]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.25479043  1.21649683 -0.02430925  0.66123605]
 [-0.96031344  0.24185427 -1.61092103  0.9219358 ]
 [-0.32711041 -0.51152277 -0.91544276  0.04756243]
 [ 1.33730173  0.28005019  2.32172537  0.38202828]]


[[ 0.00124359  0.8928653   0.43184304  0.83894706]
 [ 0.74307823  0.2582587   0.03652358  0.55017567]
 [ 0.52906871  0.55183744  0.28640068  0.50959206]
 [ 0.29206061  0.79572272  0.91007018  0.75140786]]




In [34]:
a=tf.constant([[1,2],[3,4]])

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [36]:
b=tf.constant([[10],[100]])

In [37]:
b

<tf.Tensor 'Const_8:0' shape=(2, 1) dtype=int32>

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result=tf.matmul(a,b)

In [40]:
sess.run(result)

array([[210],
       [430]])

In [41]:
result.eval()

array([[210],
       [430]])